config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :books
  resources :users, only: [:index, :show, :edit, :new, :create, :update]
  get '/home/about', to: 'homes#about'

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true,
                   length: { maximum: 200 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @users = User.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render action: :index
    end
  end

  def edit
    @book = Book.find(params[:id])

    if current_user != @book.user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "You have update book successfully."
      redirect_to book_path(@book.id)
    else
      render action: :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def corrent_user
    @book = Book.find(params[:id])
    if current_uesr != @book.user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_olduserinfo.html.erb
<div class= "col-md-3">
 <h2>User info</h2>
 <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size: '100x100' %>
 <table class="table">
  <tbody>
   <tr></tr>
   <tr>
    <th>name</th>
    <th><%= user.name %></th>
   </tr>
   <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
   </tr>
  </tbody>
 </table>
 <div class="row">
    <%= link_to '', edit_user_path(user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
 </div>

 <h2 class="mt-3">New book</h2>
 <%= form_with model:@book, local:true do |f|%>
  <div class="form-group">
     <%= f.label :title,'Title' %>
     <%= f.text_field :title, class: 'form-control book_body' %>
  </div>

  <div class="form-group">
     <%= f.label :body, 'Opinion' %>
     <%= f.text_area :body, class: 'form-control book_body' %>
  </div>

  <div class="form-group">
     <%= f.submit "Create Book", class: 'btn btn-success' %>
  </div>
 <% end %>
</div>

app/views/books/_userinfo.html.erb
<div class= "col-md-3">
 <h2>User info</h2>
 <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size: '100x100' %>
 <table class="table">
  <tbody>
   <tr></tr>
   <tr>
    <th>name</th>
    <th><%= user.name %></th>
   </tr>
   <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
   </tr>
  </tbody>
 </table>
 <div class="row">
    <%= link_to '', edit_user_path(current_user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
 </div>

 <h2 class="mt-3">New book</h2>
 <%= form_with model:@book, local:true do |f|%>
  <div class="form-group">
     <%= f.label :title,'Title' %>
     <%= f.text_area :body, class: 'form-control book_body' %>
  </div>

  <div class="form-group">
     <%= f.label :body, 'Opinion' %>
     <%= f.text_field :title, class: 'form-control book_body' %>
  </div>

  <div class="form-group">
     <%= f.submit "Create Book", class: 'btn btn-success' %>
  </div>
 <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
            <h1>Editing Book</h1>
            <%= form_with model:@book, local:true do |f| %>
             <% if @book.errors.any? %>
              <div id="error_explanation">
                  <h3>
                   <%= @book.errors.count %>
                   error prohibited this obj from being saved:
                  </h3>
                  <ul>
                      <% @book.errors.full_messages.each do |message| %>
                       <li><%= message %></li>
                      <% end %>
                  </ul>
              </div>
            <% end %>
            <div class="form-group">
                <%= f.label :title, 'Title' %>
                <%= f.text_field :title, class: 'form-control book_title' %>
            </div>

            <div class="form-group">
                <%= f.label :title, 'Opinion' %>
                <%= f.text_area :body, class: 'form-control book_body' %>
            </div>

            <div class="form-group">
                <%= f.submit "Update Book", class: 'btn btn-success' %>
            </div>
           <% end %>

           <%= link_to "Show", book_path(@book.id), class: 'Book_id' %>
            |
           <%= link_to "Back", books_path, class: 'back' %>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= @book.errors.count %>
        error prohibited this obj from being saved:
      </h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="row">
      <%= render 'users/userinfo', book:@book, user:current_user %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                 <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: '40x40' %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                 <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
</div>

app/views/books/new.html.erb
<h2 class="mt-3">New book</h2>
<!-- form_with部分 -->
<%= form_with model:@book, local:true do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'CreateBook' %>
<% end %>

app/views/books/show.html.erb
<div class="container">
    <div class="row">
        <%= render 'users/userinfo', book:@book_new, user:@user %>
        <div class="col-md-8 offset-md-1">
            <h2>Book detail</h2>
            <table class="table">
                <tbody>
                    <tr>
                        <td>
                            <%= link_to user_path(@user.id) do %>
                             <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size: '40x40' %>
                             <br/>
                             <%= @user.name %>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to book_path(@book.id) do %>
                              <%= @book.title %>
                            <% end %>
                        </td>
                        <td>
                            <%= @book.body %>
                        </td>
                        <% if @book.user == current_user %>
                         <td>
                             <%= link_to 'Edit', edit_book_path, class: 'btn btn-sm btn-success' %>
                         </td>
                         <td>
                             <%= link_to 'Destroy', book_path(@book.id), class: 'btn btn-sm btn-danger', method: :delete, "data-confirm" => "本当に消しますか？" %>
                         </td>
                        <% end %>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>